# A string used to distinguish different Supabase projects on the same machine.
project_id = "configurable-mlm-system"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = true

[db]
port = 54322
major_version = 15
